blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/just-the-docs/just-the-docs/discussions
    about: Ask questions and discuss with other community members
